### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by blockchaindevsh**
This PR merges with op-geth commit 110c433a2469, which is the version referenced by latest monorepo.

Conflicting files:

image

### CODE REVIEW

**Review by qizhou — APPROVED** [review]

**Comment by qzhodl** [comment]
> This PR merges with op-geth commit [110c433](https://github.com/ethstorage/op-geth/commit/110c433a24692faecce2a495c5f45efc8fcc3c33), which is the version referenced by latest monorepo.
> 
> Conflicting files:
> 
> image

Where can we find the referenced version of op-geth in the monorepo?

**Comment by blockchaindevsh** [comment]
> Where can we find the referenced version of op-geth in the monorepo?

In `go.mod` at the root of monorepo.

**Review by qzhodl — APPROVED** [review]

**Comment by qizhou** [comment]
What is the status of the PR?

**Comment by blockchaindevsh** [comment]
> What is the status of the PR?

It was ready to merge, but now has conflict because of recent change. The optimal merge process is that we merge it after we merge [this](https://github.com/ethstorage/op-geth/pull/12) one, otherwise the conflict will occur twice.

**Review by pochenai — APPROVED** [review]

**Pull request merged**
